version: '3.7'

services:

  mariadb:
    image: mariadb
    environment: 
      - MYSQL_ROOT_PASSWORD=root
  
  pa:
    image: php:7.2-apache
    build: .
    volumes:
     - ./dm/:/var/www/html
    ports:
     - 8081:80
    depends_on:
    - mariadb
    
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    volumes:
     - ./dm/:/var/www/html
    depends_on:
      - mariadb

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025
    environment:
     - MH_STORAGE=maildir
    depends_on:
      - mariadb
